#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.6.0
// Descriptor size: 116 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 7 |
// +----------+-------+-------------------+
// |        2 | Input |                 3 |
// +----------+-------+-------------------+
// |        3 | Input |                 7 |
// +----------+-------+-------------------+
static const uint8_t hidReportDescriptor[] ALIGNED(4) =
{
    0x05, 0x01,          // UsagePage(Generic Desktop[0x0001])
    0x09, 0x06,          // UsageId(Keyboard[0x0006])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x05, 0x07,          //     UsagePage(Keyboard/Keypad[0x0007])
    0x19, 0xE0,          //     UsageIdMin(Keyboard LeftControl[0x00E0])
    0x29, 0xE7,          //     UsageIdMax(Keyboard Right GUI[0x00E7])
    0x15, 0x00,          //     LogicalMinimum(0)
    0x25, 0x01,          //     LogicalMaximum(1)
    0x95, 0x08,          //     ReportCount(8)
    0x75, 0x01,          //     ReportSize(1)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x19, 0x01,          //     UsageIdMin(ErrorRollOver[0x0001])
    0x29, 0x65,          //     UsageIdMax(Keyboard Application[0x0065])
    0x15, 0x01,          //     LogicalMinimum(1)
    0x25, 0x65,          //     LogicalMaximum(101)
    0x95, 0x06,          //     ReportCount(6)
    0x75, 0x07,          //     ReportSize(7)
    0x81, 0x00,          //     Input(Data, Array, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,          //     ReportCount(1)
    0x75, 0x06,          //     ReportSize(6)
    0x81, 0x03,          //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                // EndCollection()
    0x05, 0x01,          // UsagePage(Generic Desktop[0x0001])
    0x09, 0x02,          // UsageId(Mouse[0x0002])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x02,          //     ReportId(2)
    0x09, 0x01,          //     UsageId(Pointer[0x0001])
    0xA1, 0x00,          //     Collection(Physical)
    0x09, 0x30,          //         UsageId(X[0x0030])
    0x09, 0x31,          //         UsageId(Y[0x0031])
    0x15, 0x80,          //         LogicalMinimum(-128)
    0x25, 0x7F,          //         LogicalMaximum(127)
    0x95, 0x02,          //         ReportCount(2)
    0x75, 0x08,          //         ReportSize(8)
    0x81, 0x06,          //         Input(Data, Variable, Relative, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x09,          //         UsagePage(Button[0x0009])
    0x19, 0x01,          //         UsageIdMin(Button 1[0x0001])
    0x29, 0x03,          //         UsageIdMax(Button 3[0x0003])
    0x15, 0x00,          //         LogicalMinimum(0)
    0x25, 0x01,          //         LogicalMaximum(1)
    0x95, 0x03,          //         ReportCount(3)
    0x75, 0x01,          //         ReportSize(1)
    0x81, 0x02,          //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                //     EndCollection()
    0x95, 0x01,          //     ReportCount(1)
    0x75, 0x05,          //     ReportSize(5)
    0x81, 0x03,          //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                // EndCollection()
    0x06, 0x00, 0xFF,    // UsagePage(Vendor Usage Page 1[0xFF00])
    0x09, 0xFF,          // UsageId(Vendor Usage 1[0x00FF])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x03,          //     ReportId(3)
    0x09, 0xFF,          //     UsageId(Vendor Usage 1[0x00FF])
    0x26, 0xFF, 0x00,    //     LogicalMaximum(255)
    0x95, 0x07,          //     ReportCount(7)
    0x75, 0x08,          //     ReportSize(8)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_INPUT1_ID (1)
struct HidReportInput1
{
    uint8_t ReportId; // = HID_REPORT_INPUT1_ID;
    uint8_t Payload[7];
};

#define HID_REPORT_INPUT2_ID (2)
struct HidReportInput2
{
    uint8_t ReportId; // = HID_REPORT_INPUT2_ID;
    uint8_t Payload[3];
};

#define HID_REPORT_INPUT3_ID (3)
struct HidReportInput3
{
    uint8_t ReportId; // = HID_REPORT_INPUT3_ID;
    uint8_t Payload[7];
};

#pragma pack(pop)
